CREATE DATABASE IF NOT EXISTS surakshya_nepal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE surakshya_nepal;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(120) NOT NULL, mobile VARCHAR(10) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('citizen','hospital_admin','police','municipality','admin') NOT NULL DEFAULT 'citizen', district VARCHAR(80) NULL, municipality VARCHAR(120) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE hospitals (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, type ENUM('Government','Private','Community','Specialized') NOT NULL, province VARCHAR(50) NOT NULL, district VARCHAR(80) NOT NULL, municipality VARCHAR(120) NOT NULL, address VARCHAR(255) NOT NULL, emergency_contact VARCHAR(30) NOT NULL, latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(district), INDEX(province));
CREATE TABLE hospital_status (hospital_id INT UNSIGNED PRIMARY KEY, total_beds SMALLINT UNSIGNED NOT NULL, beds_available SMALLINT UNSIGNED NOT NULL, icu_available SMALLINT UNSIGNED NOT NULL, emergency_available SMALLINT UNSIGNED NOT NULL, ambulances_available SMALLINT UNSIGNED NOT NULL, blood_bank ENUM('Available','Limited','Unavailable') NOT NULL, waiting_minutes SMALLINT UNSIGNED NOT NULL, emergency_status ENUM('Open','Busy','Full') NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(hospital_id) REFERENCES hospitals(id) ON DELETE CASCADE);
CREATE TABLE doctors (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, hospital_id INT UNSIGNED NOT NULL, full_name VARCHAR(120) NOT NULL, degree VARCHAR(120) NOT NULL, department VARCHAR(100) NOT NULL, specialization VARCHAR(100) NOT NULL, experience_years TINYINT UNSIGNED NOT NULL, languages VARCHAR(255) NOT NULL, opd_time VARCHAR(80) NULL, consultation_time VARCHAR(80) NULL, room_number VARCHAR(40) NULL, available_today BOOLEAN NOT NULL DEFAULT TRUE, status ENUM('Available','Busy','Off Duty') NOT NULL DEFAULT 'Available', FOREIGN KEY(hospital_id) REFERENCES hospitals(id) ON DELETE CASCADE, INDEX(specialization));
CREATE TABLE reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tracking_id VARCHAR(25) NOT NULL UNIQUE, user_id INT UNSIGNED NOT NULL, category VARCHAR(80) NOT NULL, title VARCHAR(180) NOT NULL, description TEXT NOT NULL, priority ENUM('Normal','High','Emergency') NOT NULL, latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, address VARCHAR(255) NULL, is_anonymous BOOLEAN NOT NULL DEFAULT FALSE, status ENUM('Received','Under Review','Assigned','In Progress','Resolved','Closed','Rejected') NOT NULL DEFAULT 'Received', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE sos_incidents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, address VARCHAR(255) NULL, status ENUM('Received','Officer Assigned','On The Way','Reached','Closed') NOT NULL DEFAULT 'Received', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));

INSERT INTO hospitals(name,type,province,district,municipality,address,emergency_contact) VALUES
('Bir Hospital','Government','Bagmati','Kathmandu','Kathmandu Metropolitan City','Mahaboudha, Kathmandu','01-4221119'),('Patan Hospital','Community','Bagmati','Lalitpur','Lalitpur Metropolitan City','Lagankhel, Lalitpur','01-5522295'),('Teaching Hospital','Specialized','Bagmati','Kathmandu','Kirtipur Municipality','Maharajgunj, Kathmandu','01-4412303'),('Bharatpur Hospital','Government','Bagmati','Chitwan','Bharatpur Metropolitan City','Bharatpur, Chitwan','056-527959'),('Pokhara Academy Hospital','Government','Gandaki','Kaski','Pokhara Metropolitan City','Pokhara, Kaski','061-522674');
INSERT INTO hospital_status VALUES (1,120,42,8,12,4,'Available',18,'Open',NOW()),(2,84,28,6,7,3,'Available',25,'Busy',NOW()),(3,156,63,14,19,6,'Limited',35,'Busy',NOW()),(4,68,22,5,9,2,'Available',15,'Open',NOW()),(5,74,31,7,10,3,'Available',20,'Open',NOW());
INSERT INTO doctors(hospital_id,full_name,degree,department,specialization,experience_years,languages,opd_time,consultation_time,room_number,available_today,status) VALUES (1,'Dr. Anil Shrestha','MD, DM','Cardiology','Cardiology',14,'Nepali, English','09:00–16:00','09:00–16:00','204',1,'Available'),(1,'Dr. Sita Karki','MBBS, MS','Orthopedics','Orthopedic Surgery',10,'Nepali, English','10:00–15:00','10:00–15:00','112',1,'Busy'),(2,'Dr. Ramesh Bista','MBBS, MD','Emergency','Emergency Medicine',12,'Nepali, English, Hindi','24 hours','24 hours','Emergency Unit',1,'Available'),(2,'Dr. Nisha Joshi','MBBS, MD','Pediatrics','Pediatrics',8,'Nepali, English','09:00–15:00','09:00–15:00','309',1,'Available'),(3,'Dr. Maya Gurung','MBBS, MS','Neurology','Neurology',16,'Nepali, English','11:00–16:00','11:00–16:00','415',1,'Available');
