<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hospital Dashboard | Surakshya Nepal</title><style>
body{margin:0;background:#f5f7fb;color:#16233d;font:15px Arial,sans-serif}.wrap{max-width:960px;margin:45px auto;padding:0 20px}.head{background:linear-gradient(110deg,#00245e,#004db5);color:#fff;padding:30px;border-radius:20px}.head h1{margin:0 0 8px}.card{background:#fff;border:1px solid #e4e9f2;border-radius:16px;padding:22px;margin-top:20px;box-shadow:0 5px 20px #1d315709}label{display:block;font-weight:bold;margin:12px 0 6px}input,select,textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #ccd5e4;border-radius:8px;font:inherit}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}button{background:#dc143c;color:#fff;border:0;border-radius:8px;padding:12px 16px;font-weight:bold;cursor:pointer;margin-top:16px}.secondary{background:#003893}#message{padding:12px 0;font-weight:bold}.hidden{display:none}@media(max-width:600px){.grid{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><section class="head"><h1>🇳🇵 Hospital Live Dashboard</h1><p>Update hospital capacity, emergency status, and public announcements.</p></section>
<section class="card" id="login"><h2>Administrator login</h2><p>Use an authorized Hospital Administrator or System Administrator account.</p><label>Mobile</label><input id="mobile" value="9800000000"><label>Password</label><input id="password" type="password" value="Admin@12345"><button onclick="signIn()">Secure sign in</button></section>
<section class="card hidden" id="dashboard"><h2>Live status update</h2><label>Hospital</label><select id="hospital"></select><div class="grid"><div><label>Total beds</label><input id="total_beds" type="number"></div><div><label>Available beds</label><input id="beds_available" type="number"></div><div><label>ICU available</label><input id="icu_available" type="number"></div><div><label>Emergency beds</label><input id="emergency_available" type="number"></div><div><label>Ambulances ready</label><input id="ambulances_available" type="number"></div><div><label>Waiting time (minutes)</label><input id="waiting_minutes" type="number"></div></div><label>Blood bank</label><select id="blood_bank"><option>Available</option><option>Limited</option><option>Unavailable</option></select><label>Emergency status</label><select id="emergency_status"><option>Open</option><option>Busy</option><option>Full</option></select><button onclick="updateStatus()">Publish live update</button><hr><h2>Hospital announcement</h2><label>Title</label><input id="announcement-title" placeholder="e.g. Emergency services active"><label>Message</label><textarea id="announcement-message" rows="3"></textarea><button class="secondary" onclick="announce()">Publish announcement</button><p id="message"></p></section></main>
<script>
const api='api/index.php?route=';let jwt='',records=[];const request=(route,method='GET',data)=>fetch(api+route,{method,headers:{'Content-Type':'application/json',...(jwt?{Authorization:'Bearer '+jwt}:{})},body:data?JSON.stringify(data):undefined}).then(r=>r.json());
async function signIn(){const r=await request('auth/login','POST',{mobile:mobile.value,password:password.value});if(!r.ok)return alert(r.error);jwt=r.token;login.classList.add('hidden');dashboard.classList.remove('hidden');records=(await request('hospitals')).data;hospital.innerHTML=records.map(x=>`<option value="${x.id}">${x.name} — ${x.district}</option>`).join('');loadForm();hospital.onchange=loadForm}
function loadForm(){const h=records.find(x=>x.id==hospital.value);['total_beds','beds_available','icu_available','emergency_available','ambulances_available','waiting_minutes','blood_bank','emergency_status'].forEach(k=>document.getElementById(k).value=h[k])}
async function updateStatus(){const data={};['total_beds','beds_available','icu_available','emergency_available','ambulances_available','waiting_minutes','blood_bank','emergency_status'].forEach(k=>data[k]=document.getElementById(k).value);const r=await request(`hospitals/${hospital.value}/status`,'PATCH',data);message.textContent=r.ok?'Live information published.':r.error}
async function announce(){const r=await request(`hospitals/${hospital.value}/announcements`,'POST',{title:document.getElementById('announcement-title').value,message:document.getElementById('announcement-message').value});message.textContent=r.ok?'Announcement published.':r.error}
</script></body></html>
